module FriendlySlug
  module ActiveRecord
    module Base
      def build_friendly_slug(*attribute_list, use: nil)
        instance_variable_set("@_friendly_attribute_list", attribute_list)
        instance_variable_set("@_friendly_use_key", use)

        instance_eval do
          # Attribute list generated by passing in attributes that will
          # create the slug.
          #
          # Ex. :title, :author, :id
          def _friendly_attribute_list
            @_friendly_attribute_list
          end

          _friendly_attribute_list.each do |attribute|
            define_singleton_method :"_friendly_#{attribute.to_s}_key" do
              instance_variable_set("@_friendly_#{attribute.to_s}_key", attribute)
            end
          end

          # Key used to indentify retrieval method of the record.
          #
          # Options: :first, :last, or :database
          def _friendly_use_key
            @_friendly_use_key
          end

          # Method used in the controller to find the slugged object.
          def find_slugged(id)
            find(id.split("-").send(_friendly_use_key))
          end
        end

        class_eval do
          before_save :_update_slug

          # Overload the default to_param method provided by Active Model.
          # If the model responds to slug method, it will check to see if
          # the slug is nil or if the attribute has recently changed. It
          # will generate a new URL friendly slug there is no slug currently
          # or the previously mentioned logic is true.
          def to_param
            if self.respond_to?(:slug)
              if self.slug.nil? || _unique_attribute_changed?
                _create_slug
              else
                self.slug
              end
            else
              _create_slug
            end
          end

          private
          # Send the attribute to the model to retrieve its value.
          def _lookup_key(k)
            k.is_a?(Symbol)? self.send(k) : k.to_s 
          end

          # Updates the slug based upon the _friendly_use_key method.
          # If the slug is already stored in the database and
          # another record has the same slug, it will append a
          # hashed value to uniquely identify it.
          def _update_slug
            if self.class._friendly_use_key == :database
              current_slug = self.to_param
              unless _slug_exists?(current_slug)
                self.slug = current_slug
              else
                self.slug = [current_slug.to_s, SecureRandom.hex(6)].join("-")
              end
            end
          end

          # Generates the slug based upon the attributes given and sanitizes it
          # for URL and SEO friendlyness.
          def _create_slug
            fresh_slug = self.class._friendly_attribute_list.map do |attribute|
              _lookup_key(self.class.send("_friendly_#{attribute.to_s}_key")).to_s
            end.
              join("-").
              gsub(/<\/?[^>]*>|[^\.\w\s-]/, '').
              strip.downcase.gsub(/\s{1,}|\./, '-').
              gsub(/-{2,}/, "-")

            fresh_slug[-1] == "-" ? fresh_slug[0...-1] : fresh_slug
          end

          def _unique_attribute_changed?
            self.send("#{self.class.send("_friendly_attribute_list").first.to_s}_changed?".to_sym)
          end

          # Verify that the slug is unique.
          def _slug_exists?(current_slug)
            self.class.where("slug = ? AND id != ?", current_slug, self.id.nil? ? "NULL" : self.id).any? 
          end
        end
      end
    end
  end
end

class ActiveRecord::Base
  extend FriendlySlug::ActiveRecord::Base
end
